import type {Metadata} from "next";
import "@theme/globals.css";
import {Settings} from "@theme/settings";
import Header from "@theme/header";
import Footer from "@theme/footer";
import {getLocale} from "next-intl/server";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {

    let bodyClass = Settings.bodyClass;
    Settings.fonts.forEach(font => {
        bodyClass = bodyClass.concat(" ", font.variable)
    });
    const locale = await getLocale();

    return (
        //TODO: change lang to actual language
        <html lang={locale}>
        <body
            className={`${bodyClass} antialiased`}
        >
        <Header/>
        {children}
        <Footer/>
        </body>
        </html>
    );
}
