//TODO:
// import css from theme
//
import type { Metadata } from "next";
import "./globals.css";
import { Fonts } from "@theme/settings";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  let bodyClass = "";
  Fonts.forEach(font => {
    bodyClass = bodyClass.concat(" ", font.variable)
  });

  return (
    //TODO: change lang to actual language
    <html lang="en">
      <body
        className={`${bodyClass} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
