import type {Metadata} from "next";
import {Figtree} from "next/font/google";
import "./globals.css";

const figtree = Figtree({
    variable: "--font-figtree",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${figtree.variable} antialiased h-full bg-slate-50 dark:bg-slate-950 text-slate-950 dark:text-slate-50`}
        >
        {children}
        </body>
        </html>
    );
}
